site_name: G1 Embarcados - Entrega 04
repo_url: https://github.com/UnBArqDsw2025-1-Turma01/2025.1-T01-_G1_Embarcado_Entrega_04
repo_name: 2025.1-T01-_G1_Embarcado_Entrega_04
extra_css:
  - css/custom-general.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - js/interactive.js
  - js/perfect_embed.js

plugins:
  - search
  - mermaid2

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.index
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - header.autohide
    - announce.dismiss

  language: pt-BR
  font:
    text: Roboto Mono
    code: Roboto Mono
    heading: Montserrat

  palette:
    - scheme: slate
      primary: deep purple
      accent: deep orange

nav:
  - Home: index.md
  - Projetos:
      - Projeto: Projeto/Projeto.md

  - Base:
      - 1. Desenho de Software (Base): Base/1.Base.md
      - 1.1. Design Sprint: Base/1.1.DesignSprint.md
      - 1.1.1. Entender: Base/1.1.1.Entender.md
      - 1.1.2. Divergir: Base/1.1.2.Divergir.md
      - 1.1.3. Decidir: Base/1.1.3.Decisao.md
      - 1.1.4. Prototipar: Base/1.1.4.Prototipar.md
      - 1.1.5. Testar: Base/1.1.5.Testar.md
      - 1.2. Artefato Generalista: Base/1.2.ArtefatoGeneralista.md
      - 1.2.1. Léxicos: Base/1.2.1.Lexicos.md
      - 1.2.2. 5W2H: Base/1.2.2.5W2H.md
      - 1.2.3. Ishikawa: Base/1.2.3.Ishikawa.md
      - 1.2.4. StoryBoard: Base/1.2.4.StoryBoard.md
      - 1.3. Modelagem BPMN: Base/1.3.ModelagemBPMN.md
      - 1.4. Participações: Base/1.4.ParticipacoesBase.md
      - 1.5. Iniciativas Extras: Base/1.5.IniciativasExtras.md
      - 1.5.1. Proto-personas: Base/1.5.1.Personas.md

  - Modelagem:
      - 2. Desenho de Software (Modelagem): Modelagem/2.Modelagem.md
      - 2.1. Modelagem UML Estática: Modelagem/2.1.ModelagemEstatica.md
      - 2.1.1. Diagrama de Classes: Modelagem/2.1.ModelagemEstatica.md
      - 2.2. Modelagem UML Dinâmica: Modelagem/2.2.ModelagemDinamica.md
      - 2.2.1. Diagrama de Comunicação: Modelagem/2.2.1.Comunicacao.md
      - 2.2.2. Diagrama de Estados: Modelagem/2.2.ModelagemDinamica.md
      - 2.3. Modelagem UML Organizacional ou Casos de Uso: Modelagem/2.3.ModelagemOrganizacionalCasosDeUso.md
      - 2.4. Participações - Modelagem: Modelagem/2.4.ParticipacoesModelagem.md
      - 2.5. Iniciativas Extras - Modelagem: Modelagem/2.5.IniciativasExtras.md

  - Padrões de Projeto:
      - 3. Desenho de Software (Padrões de Projeto): PadroesDeProjeto/3.PadroesDeProjeto.md
      - 3.1. Padrões de Projeto GoFs Criacionais: PadroesDeProjeto/3.1.GoFsCriacionais.md
      - 3.2. Padrões de Projeto GoFs Estruturais: PadroesDeProjeto/3.2.GoFsEstruturais.md
      - 3.3. Padrões de Projeto GoFs Comportamentais: PadroesDeProjeto/3.3.GoFsComportamentais.md
      - 3.4. Participações - Padrões de Projeto: PadroesDeProjeto/3.4.ParticipacoesPadroes.md
      - 3.5. Iniciativas Extras - Padrões de Projeto: PadroesDeProjeto/3.5.IniciativasExtras.md
      - 3.5.1. Iniciativas Extras - Diagrama de Atividades: PadroesDeProjeto/3.5.1.DiagramaDeAtividades.md
      - 3.5.2. Iniciativas Extras - Diagrama de Sequência: PadroesDeProjeto/3.5.2.DiagramaDeSequência.md
      - 4.0. Embarcado com Padrões de Projeto: PadroesDeProjeto/4.0. Embarcado.md

  - Arquitetura e Reutilizacao:
      - 4. Desenho de Software (Arquitetura & Reutilização de Software): ArquiteturaReutilizacao/4.ArquiteturaReutilizacao.md
      - 4.1. DAS: ArquiteturaReutilizacao/4.1.DAS.md
      - 4.2. Reutilização de Software: ArquiteturaReutilizacao/4.2.ReutilizacaoDeSoftware.md
      - 4.3. Participações - Arquitetura & Reutilização de Software: ArquiteturaReutilizacao/4.3.ParticipacoesArqReutilizacao.md
